# Generated by Django 4.0.2 on 2022-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product_description', models.CharField(max_length=50, verbose_name='Product Description')),
                ('product_date', models.DateTimeField(verbose_name='Product Date')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('product_image', models.ImageField(default='', upload_to='shop_app/images', verbose_name='Image')),
            ],
        ),
    ]
