# Generated by Django 4.0.2 on 2022-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('product', 'Product'), ('material', 'Material')], default='product', max_length=25, verbose_name='Product Category'),
        ),
    ]
