# Generated by Django 4.0.2 on 2022-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('desc', models.CharField(max_length=500, verbose_name='Description')),
            ],
        ),
    ]
