# Generated by Django 4.0.3 on 2022-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_details',
            field=models.CharField(default='', max_length=5000, verbose_name='Item Details'),
        ),
    ]
