# Generated by Django 4.0.3 on 2022-03-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_order_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(editable=False, to='shop_app.product'),
        ),
    ]
