# Generated by Django 4.0.3 on 2022-03-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='shop_app.product'),
        ),
    ]
