# Generated by Django 4.0.3 on 2022-03-14 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_alter_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('order_update_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('update_desc', models.CharField(default='', max_length=5000, verbose_name='Update Description')),
                ('update_time', models.DateField(auto_now_add=True, verbose_name='Update Time')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.order', verbose_name='Order')),
            ],
        ),
    ]
