# Generated by Django 4.0.3 on 2022-03-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0, verbose_name='Order Price'),
        ),
    ]
