# Generated by Django 4.0.2 on 2022-11-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_alter_comments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='shop_app.Product'),
        ),
    ]
